update the path of pic in doc
FederatedAI/FATE pull request #3524
Opened 2021-12-08 09:39 UTC by gxcuit

Signed-off-by: gxcuit <gxcuit@163.com>

Fixes  the path of pic in doc(homo_framework.md)

Changes:

1.

2.

3.

2021-12-08 10:19 UTC, weiwee requested changes
maybe we could makes github and [mkdocs](https://fate--3524.org.readthedocs.build/en/3524/) both happy in this way

2021-12-08 10:19 UTC, weiwee commented on doc/federatedml_component/homo_framework.md
> +<img src="../images/random_padding_cipher.png" alt="random_padding_cipher" width="600" height="600" /><br/>
```suggestion
![random_padding_cipher](../images/random_padding_cipher.png)
```

2021-12-08 10:19 UTC, weiwee commented on doc/federatedml_component/homo_framework.md
> +<img src="../images/paillier_cipher.png" alt="paillier_cipher" width="450" height="600" /><br/>
```suggestion
![paillier_cipher](../images/paillier_cipher.png)
```

2021-12-09 02:56 UTC, weiwee approved these changes

2021-12-09 02:59 UTC, dylan-fan approved these changes

2021-12-09 03:00 UTC, merged