Feature 1.9.0 fate arch fix
FederatedAI/FATE pull request #4034
Opened 2022-06-14 06:23 UTC by dylan-fan

Fixes  ISSUE #xxx

Changes:

1.

2.

3.

2022-06-14 06:48 UTC, zhihuiwan approved these changes

2022-06-14 06:52 UTC, jat001 commented
```python
if key is None:
_config = {}
if isinstance(config, dict):
    _config.update(config)
if isinstance(local_config, dict):
    _config.update(local_config)
return _config
```

2022-06-14 06:54 UTC, jat001 requested changes
```python
if key is None:
    _config = {}
    if isinstance(config, dict):
        _config.update(config)
    if isinstance(local_config, dict):
        _config.update(local_config)
    return _config
```

2022-06-16 02:47 UTC, jat001 approved these changes

2022-06-16 02:48 UTC, merged